services:
  redis:
    # image: redislabs/rejson
    image: redis/redis-stack:latest
    ports:
    - 6379:6379

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10
  django-app:
    build:
      context: .
      dockerfile: Dockerfile-django
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
    - 3000:3000
    depends_on:
      redis:
        condition: service_healthy
  exchanges-api:
    build:
      context: .
      dockerfile: Dockerfile-exchanges
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
    - 8000:8000
    depends_on:
      redis:
        condition: service_healthy